import type { NextPage, GetStaticProps } from 'next'
import { Helmet } from "react-helmet";
import Head from "next/head";
import axios from "axios";
import styled from "styled-components";

// components
import FirstHero from "../components/FirstHero/FirstHero";



export const getStaticProps: GetStaticProps = async (context) => {


  return {
    props: {

    },
  }
}

interface Context {

}

const Home: NextPage<Context> = ({ }) => {

  return (
    <Wrapper >

      <Head>
        <title >Sturlei Homepåge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainWrapper>
        <FirstHero
          leftContent={
            <Wrapper>
              <HeaderOne>Making it happen</HeaderOne>
              <PhraseOne>By doing less. Don&apos;t overdo things</PhraseOne>
            </Wrapper>
          }
          rightContent={
            <Wrapper>

            </Wrapper>
          }
        />
      </MainWrapper>


      <FooterWrapper >

      </FooterWrapper>
    </Wrapper >
  )
}





const Wrapper = styled.div`

`;

const MainWrapper = styled.main`

`;

const FooterWrapper = styled.footer`

`;

const HeaderOne = styled.h1`
  position: relative;
  font-size: 8rem;
  display: flex;
  margin-bottom: 3.5rem;
  &:after{
    position: absolute;
    height: 2rem;
    width: 30%;
    content: '';
    left: 0;
    top: calc(100% + .2rem);
    background-color: currentColor;

  }

`;
const PhraseOne = styled.p`
  font-size: 2rem;

`;


export default Home
