import type { NextPage, GetStaticProps } from 'next'
import { Helmet } from "react-helmet";
import Head from "next/head";
import axios from "axios";
import styled from "styled-components";
import { useState } from 'react';



export const getStaticProps: GetStaticProps = async (context) => {


  return {
    props: {

    },
  }
}

interface Context {

}

const Home: NextPage<Context> = ({ }) => {

  return (
    <Wrapper >

      <Head>
        <title > Hem - Codemine Media AB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainWrapper>

      </MainWrapper>


      <FooterWrapper >

      </FooterWrapper>
    </Wrapper >
  )
}





const Wrapper = styled.div`

`;

const MainWrapper = styled.main`

`;

const FooterWrapper = styled.footer`

`;
export default Home
